### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by aaronychu** [CrazyShipOne/nextcloud_talk_pybot#1]
```Traceback (most recent call last):
  File "/Users/ayz/nextcloud_talk_pybot/ncbot/poll_runner.py", line 43, in deal_unread_chats
    send_response(chatC)
  File "/Users/ayz/nextcloud_talk_pybot/ncbot/poll_runner.py", line 55, in send_response
    if nc_agent.send_message(chat.conversation_token, chat.chat_id, chat.response, chat.chat_message,chat.user_id, chat.chat_type == ncconstants.chat_type_user):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayz/nextcloud_talk_pybot/ncbot/nc_helper.py", line 60, in send_message
    response = rutil.post_response(self.final_url_v1(f'/chat/{token}'), data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayz/nextcloud_talk_pybot/ncbot/request_util.py", line 25, in post_response
    return response_check(response, uri, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayz/nextcloud_talk_pybot/ncbot/request_util.py", line 38, in response_check
    raise Exception(f"requests to {uri} failed, status code is {response.status_code}, data:\n{json_data}")
Exception: requests to /ocs/v2.php/apps/spreed/api/v1/chat/4dpmc2un failed, status code is 500, data:
{'message': '@"admin" \nYou should type !Plugin:Function to talk with me.\n\nCurrent supported plugins are:\nsetting\nhface\nopenai\n\nType !Plugin to see detail about plugin.\nThe last command will be remembered if capable, so you should not type the command first next time.', 'replyTo': 1400}```
Nextcloud spreed version 17.1

**Comment by CrazyShipOne** [comment]
Is there anything might be related in Nextcloud's system log?

**Comment by SandorUK** [comment]
Same issue here on 27.1.1.,

Running via docker, provided url, user name, app password, open AI key. Seeing this in docker log:

```
Exception: requests to /ocs/v2.php/apps/spreed/api/v4/room failed, status code is 500, data:
2023-11-02 01:43:59,842 ERROR requests to /ocs/v2.php/apps/spreed/api/v4/room failed, status code is 500, data:
Traceback (most recent call last):
  File "/app/ncbot/poll_runner.py", line 17, in start
    unread_conversation = nc_agent.get_unread_conversation_list()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ncbot/nc_helper.py", line 22, in get_unread_conversation_list
    mesg = rutil.get_response(self.final_url_v4('room'), params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ncbot/request_util.py", line 18, in get_response
    return response_check(response, uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ncbot/request_util.py", line 38, in response_check
    raise Exception(f"requests to {uri} failed, status code is {response.status_code}, data:\n{json_data}")
```

Every 5 seconds I see the following in the system log:
```
**OCP\Security\Bruteforce\MaxDelayReached: Reached maximum delay**
/snap/nextcloud/37720/htdocs/lib/private/User/Session.php - line 431:
OC\Security\Bruteforce\Throttler->sleepDelayOrThrowOnMax()
/snap/nextcloud/37720/htdocs/lib/private/User/Session.php - line 580:
OC\User\Session->logClientIn("*** sensiti ... *")
/snap/nextcloud/37720/htdocs/lib/base.php - line 1150:
OC\User\Session->tryBasicAuthLogin()
/snap/nextcloud/37720/htdocs/ocs/v1.php - line 61:
OC::handleLogin()
/snap/nextcloud/37720/htdocs/ocs/v2.php - line 23:
require_once("/snap/nextc ... p")
```

The user does have 2FA enabled, but I am using an app password via env variable.

**Comment by CrazyShipOne** [comment]
I worked this project on NC 25. Maybe there are enhancements on security policies? Let me try it on 27 and see why it happens.

**Comment by CrazyShipOne** [comment]
Hi @SandorUK , I tested latest code with nextcloud-27.1.3(fresh installed by docker)/Talk-17.1.2/(user password or app password)/(with or without 2FA app), it all works on my test env.

Could you please try use curl and see what is reponsed:
> curl -u **your_username:app_password** -H "OCS-APIRequest: true" "http://**your.nextcloud.domain**/ocs/v2.php/apps/spreed/api/v4/room?noStatusUpdate=0&includeStatus=True"

The app_password can be replaced by user password only for users without 2FA enabled.

Besides, are there nextcloud and bot logs before rate limit happens?

**Comment by ahpeyvandi** [comment]
Hi. I use Nextcloud v27

docker run -d crazyship/nextcloud_talk_pybot --restart=always -e ENV_NAME=ENV_VALUE -e NC_BASE_URL=http://192.168.244.129:80 -e NC_USERNAME=admin -e NC_PASSWORD=123 nextcloud_talk_pybot

Error:


Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/app/ncbot/__main__.py", line 10, in <module>

    app.start()

  File "/app/ncbot/../ncbot/app.py", line 7, in start

    ncconfig.cf.checkEnv()

  File "/app/ncbot/../ncbot/config.py", line 36, in checkEnv

    raise Exception("NC_BASE_URL is not set")

Exception: NC_BASE_URL is not set

**Comment by CrazyShipOne** [comment]
Hi @ahpeyvandi, could you please try to run the container with this command:
`docker run -d --restart=always -e NC_BASE_URL=[http://192.168.244.129:80](http://192.168.244.129/) -e NC_USERNAME=admin -e NC_PASSWORD=123 --name nextcloud_talk_pybot crazyship/nextcloud_talk_pybot` 
The image name should be at the last part of command.
